/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __KPROBE_BPF_SKEL_H__
#define __KPROBE_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct kprobe_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *do_unlinkat;
		struct bpf_program *trace_enter_open;
	} progs;
	struct {
		struct bpf_link *do_unlinkat;
		struct bpf_link *trace_enter_open;
	} links;
	struct kprobe_bpf__rodata {
	} *rodata;

#ifdef __cplusplus
	static inline struct kprobe_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct kprobe_bpf *open_and_load();
	static inline int load(struct kprobe_bpf *skel);
	static inline int attach(struct kprobe_bpf *skel);
	static inline void detach(struct kprobe_bpf *skel);
	static inline void destroy(struct kprobe_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
kprobe_bpf__destroy(struct kprobe_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
kprobe_bpf__create_skeleton(struct kprobe_bpf *obj);

static inline struct kprobe_bpf *
kprobe_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct kprobe_bpf *obj;
	int err;

	obj = (struct kprobe_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = kprobe_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	kprobe_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct kprobe_bpf *
kprobe_bpf__open(void)
{
	return kprobe_bpf__open_opts(NULL);
}

static inline int
kprobe_bpf__load(struct kprobe_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct kprobe_bpf *
kprobe_bpf__open_and_load(void)
{
	struct kprobe_bpf *obj;
	int err;

	obj = kprobe_bpf__open();
	if (!obj)
		return NULL;
	err = kprobe_bpf__load(obj);
	if (err) {
		kprobe_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
kprobe_bpf__attach(struct kprobe_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
kprobe_bpf__detach(struct kprobe_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *kprobe_bpf__elf_bytes(size_t *sz);

static inline int
kprobe_bpf__create_skeleton(struct kprobe_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "kprobe_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "kprobe_b.rodata";
	s->maps[0].map = &obj->maps.rodata;
	s->maps[0].mmaped = (void **)&obj->rodata;

	/* programs */
	s->prog_cnt = 2;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "do_unlinkat";
	s->progs[0].prog = &obj->progs.do_unlinkat;
	s->progs[0].link = &obj->links.do_unlinkat;

	s->progs[1].name = "trace_enter_open";
	s->progs[1].prog = &obj->progs.trace_enter_open;
	s->progs[1].link = &obj->links.trace_enter_open;

	s->data = (void *)kprobe_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *kprobe_bpf__elf_bytes(size_t *sz)
{
	*sz = 3592;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x48\x0a\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0f\0\
\x01\0\x85\x10\0\0\xff\xff\xff\xff\x18\x01\0\0\x1a\0\0\0\0\0\0\0\0\0\0\0\xb7\
\x02\0\0\x12\0\0\0\xbf\x03\0\0\0\0\0\0\x85\0\0\0\x06\0\0\0\xb7\0\0\0\0\0\0\0\
\x95\0\0\0\0\0\0\0\x85\x10\0\0\xff\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\xb7\x02\0\0\x1a\0\0\0\xbf\x03\0\0\0\0\0\0\x85\0\0\0\x06\0\0\0\xb7\0\0\0\0\
\0\0\0\x95\0\0\0\0\0\0\0\x44\x75\x61\x6c\x20\x42\x53\x44\x2f\x47\x50\x4c\0\x20\
\x3e\x3e\x20\x74\x72\x61\x63\x65\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\
\x20\x20\x25\x64\x0a\0\x20\x7e\x7e\x7e\x20\x6b\x66\x75\x6e\x63\x3a\x20\x20\x25\
\x64\x2e\x0a\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x04\x03\0\0\x04\x03\0\0\
\x92\x02\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\x01\0\0\0\x15\0\0\x04\xa8\0\0\0\x09\0\
\0\0\x03\0\0\0\0\0\0\0\x0d\0\0\0\x03\0\0\0\x40\0\0\0\x11\0\0\0\x03\0\0\0\x80\0\
\0\0\x15\0\0\0\x03\0\0\0\xc0\0\0\0\x19\0\0\0\x03\0\0\0\0\x01\0\0\x1c\0\0\0\x03\
\0\0\0\x40\x01\0\0\x1f\0\0\0\x03\0\0\0\x80\x01\0\0\x23\0\0\0\x03\0\0\0\xc0\x01\
\0\0\x27\0\0\0\x03\0\0\0\0\x02\0\0\x2a\0\0\0\x03\0\0\0\x40\x02\0\0\x2d\0\0\0\
\x03\0\0\0\x80\x02\0\0\x30\0\0\0\x03\0\0\0\xc0\x02\0\0\x33\0\0\0\x03\0\0\0\0\
\x03\0\0\x36\0\0\0\x03\0\0\0\x40\x03\0\0\x39\0\0\0\x03\0\0\0\x80\x03\0\0\x3c\0\
\0\0\x03\0\0\0\xc0\x03\0\0\x44\0\0\0\x03\0\0\0\0\x04\0\0\x47\0\0\0\x03\0\0\0\
\x40\x04\0\0\x4a\0\0\0\x03\0\0\0\x80\x04\0\0\x50\0\0\0\x03\0\0\0\xc0\x04\0\0\
\x53\0\0\0\x03\0\0\0\0\x05\0\0\x56\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\
\x01\0\0\x0d\x05\0\0\0\x64\0\0\0\x01\0\0\0\x68\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\
\0\x01\x6c\0\0\0\x01\0\0\x0c\x04\0\0\0\0\0\0\0\0\0\0\x0d\x08\0\0\0\x4c\x01\0\0\
\0\0\0\x08\x09\0\0\0\x52\x01\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\x65\x01\0\0\x02\
\0\0\x0c\x07\0\0\0\0\0\0\0\0\0\0\x02\x0c\0\0\0\x7a\x01\0\0\x05\0\0\x04\x28\0\0\
\0\x93\x01\0\0\x09\0\0\0\0\0\0\0\x9a\x01\0\0\x0d\0\0\0\x40\0\0\0\xa5\x01\0\0\
\x0d\0\0\0\x80\0\0\0\x4a\0\0\0\x0d\0\0\0\xc0\0\0\0\xb2\x01\0\0\x0d\0\0\0\0\x01\
\0\0\xb7\x01\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\x01\0\0\0\0\x01\0\0\x0d\x05\0\0\0\
\x64\0\0\0\x0b\0\0\0\xbc\x01\0\0\x01\0\0\x0c\x0e\0\0\0\x29\x02\0\0\0\0\0\x01\
\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x10\0\0\0\x12\0\0\0\x0d\0\0\0\
\x2e\x02\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\x42\x02\0\0\0\0\0\x0e\x11\0\0\0\x01\
\0\0\0\0\0\0\0\0\0\0\x0a\x10\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x14\0\0\0\x12\0\0\
\0\x1a\0\0\0\x4a\x02\0\0\0\0\0\x0e\x15\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\
\x14\0\0\0\x12\0\0\0\x12\0\0\0\x63\x02\0\0\0\0\0\x0e\x17\0\0\0\0\0\0\0\x7b\x02\
\0\0\x01\0\0\x0f\0\0\0\0\x0a\0\0\0\0\0\0\0\0\0\0\0\x82\x02\0\0\x02\0\0\x0f\0\0\
\0\0\x16\0\0\0\0\0\0\0\x1a\0\0\0\x18\0\0\0\x1a\0\0\0\x12\0\0\0\x8a\x02\0\0\x01\
\0\0\x0f\0\0\0\0\x13\0\0\0\0\0\0\0\x0d\0\0\0\0\x70\x74\x5f\x72\x65\x67\x73\0\
\x72\x31\x35\0\x72\x31\x34\0\x72\x31\x33\0\x72\x31\x32\0\x62\x70\0\x62\x78\0\
\x72\x31\x31\0\x72\x31\x30\0\x72\x39\0\x72\x38\0\x61\x78\0\x63\x78\0\x64\x78\0\
\x73\x69\0\x64\x69\0\x6f\x72\x69\x67\x5f\x61\x78\0\x69\x70\0\x63\x73\0\x66\x6c\
\x61\x67\x73\0\x73\x70\0\x73\x73\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x6c\x6f\
\x6e\x67\0\x63\x74\x78\0\x69\x6e\x74\0\x64\x6f\x5f\x75\x6e\x6c\x69\x6e\x6b\x61\
\x74\0\x6b\x70\x72\x6f\x62\x65\x2f\x64\x6f\x5f\x75\x6e\x6c\x69\x6e\x6b\x61\x74\
\0\x2f\x68\x6f\x6d\x65\x2f\x68\x66\x69\x6e\x67\x6c\x65\x72\x2f\x68\x66\x2d\x48\
\x41\x43\x4b\x2f\x73\x72\x63\x2f\x62\x70\x66\x2f\x70\x72\x6f\x67\x72\x61\x6d\
\x73\x2f\x6b\x70\x72\x6f\x62\x65\x2f\x6b\x70\x72\x6f\x62\x65\x2e\x62\x70\x66\
\x2e\x63\0\x09\x5f\x5f\x75\x36\x34\x20\x61\x20\x3d\x20\x62\x70\x66\x5f\x6b\x66\
\x75\x6e\x63\x5f\x63\x61\x6c\x6c\x5f\x74\x65\x73\x74\x30\x28\x29\x3b\0\x09\x62\
\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x20\x7e\x7e\x7e\x20\x6b\x66\x75\
\x6e\x63\x3a\x20\x20\x25\x64\x2e\x5c\x6e\x22\x2c\x20\x61\x29\x3b\0\x69\x6e\x74\
\x20\x42\x50\x46\x5f\x4b\x50\x52\x4f\x42\x45\x28\x64\x6f\x5f\x75\x6e\x6c\x69\
\x6e\x6b\x61\x74\x2c\x20\x69\x6e\x74\x20\x64\x66\x64\x2c\x20\x73\x74\x72\x75\
\x63\x74\x20\x66\x69\x6c\x65\x6e\x61\x6d\x65\x20\x2a\x6e\x61\x6d\x65\x29\0\x5f\
\x5f\x75\x36\x34\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x6c\x6f\x6e\x67\x20\x6c\
\x6f\x6e\x67\0\x62\x70\x66\x5f\x6b\x66\x75\x6e\x63\x5f\x63\x61\x6c\x6c\x5f\x74\
\x65\x73\x74\x30\0\x73\x79\x73\x63\x61\x6c\x6c\x73\x5f\x65\x6e\x74\x65\x72\x5f\
\x6f\x70\x65\x6e\x5f\x61\x72\x67\x73\0\x75\x6e\x75\x73\x65\x64\0\x73\x79\x73\
\x63\x61\x6c\x6c\x5f\x6e\x72\0\x66\x69\x6c\x65\x6e\x61\x6d\x65\x5f\x70\x74\x72\
\0\x6d\x6f\x64\x65\0\x6c\x6f\x6e\x67\0\x74\x72\x61\x63\x65\x5f\x65\x6e\x74\x65\
\x72\x5f\x6f\x70\x65\x6e\0\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x73\x79\
\x73\x63\x61\x6c\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\
\x65\x6e\0\x09\x62\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x20\x3e\x3e\x20\
\x74\x72\x61\x63\x65\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\x20\x20\x25\
\x64\x5c\x6e\x22\x2c\x20\x61\x29\x3b\0\x09\x72\x65\x74\x75\x72\x6e\x20\x30\x3b\
\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\
\x59\x50\x45\x5f\x5f\0\x4c\x49\x43\x45\x4e\x53\x45\0\x74\x72\x61\x63\x65\x5f\
\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x5f\
\x5f\x5f\x5f\x64\x6f\x5f\x75\x6e\x6c\x69\x6e\x6b\x61\x74\x2e\x5f\x5f\x5f\x5f\
\x66\x6d\x74\0\x2e\x6b\x73\x79\x6d\x73\0\x2e\x72\x6f\x64\x61\x74\x61\0\x6c\x69\
\x63\x65\x6e\x73\x65\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x24\0\0\0\x24\0\0\0\
\x74\0\0\0\x98\0\0\0\0\0\0\0\x08\0\0\0\x78\0\0\0\x01\0\0\0\0\0\0\0\x06\0\0\0\
\xcd\x01\0\0\x01\0\0\0\0\0\0\0\x0f\0\0\0\x10\0\0\0\x78\0\0\0\x03\0\0\0\0\0\0\0\
\x8b\0\0\0\xc7\0\0\0\x0c\x48\0\0\x08\0\0\0\x8b\0\0\0\xea\0\0\0\x02\x4c\0\0\x30\
\0\0\0\x8b\0\0\0\x10\x01\0\0\x05\x40\0\0\xcd\x01\0\0\x03\0\0\0\0\0\0\0\x8b\0\0\
\0\xc7\0\0\0\x0c\x88\0\0\x08\0\0\0\x8b\0\0\0\xf0\x01\0\0\x02\x8c\0\0\x30\0\0\0\
\x8b\0\0\0\x1e\x02\0\0\x02\x90\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x14\0\0\0\x01\
\0\x08\0\x1a\0\0\0\0\0\0\0\x12\0\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x2c\0\0\0\x01\0\x08\0\0\0\0\0\0\0\0\0\x1a\0\0\0\0\0\0\0\0\0\
\0\0\x03\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\0\0\0\x12\0\x03\0\0\0\0\0\
\0\0\0\0\x40\0\0\0\0\0\0\0\xd3\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x83\0\0\0\x12\0\x05\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\xcb\0\0\0\x11\0\x07\0\
\0\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x0a\0\0\0\x07\0\0\0\x08\0\0\
\0\0\0\0\0\x01\0\0\0\x05\0\0\0\0\0\0\0\0\0\0\0\x0a\0\0\0\x07\0\0\0\x08\0\0\0\0\
\0\0\0\x01\0\0\0\x05\0\0\0\xd8\x02\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\xf0\x02\0\0\
\0\0\0\0\x03\0\0\0\x05\0\0\0\xfc\x02\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x14\x03\0\
\0\0\0\0\0\x04\0\0\0\x09\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x3c\0\0\0\
\0\0\0\0\x04\0\0\0\x03\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\
\0\0\0\x04\0\0\0\x01\0\0\0\x70\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x88\0\0\0\0\0\
\0\0\x04\0\0\0\x03\0\0\0\x98\0\0\0\0\0\0\0\x04\0\0\0\x03\0\0\0\xa8\0\0\0\0\0\0\
\0\x04\0\0\0\x03\0\0\0\x10\x12\x13\x05\x03\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\
\x6c\x2e\x42\x54\x46\x2e\x65\x78\x74\0\x5f\x5f\x5f\x5f\x64\x6f\x5f\x75\x6e\x6c\
\x69\x6e\x6b\x61\x74\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x74\x72\x61\x63\x65\x5f\
\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x2e\
\x72\x65\x6c\x6b\x70\x72\x6f\x62\x65\x2f\x64\x6f\x5f\x75\x6e\x6c\x69\x6e\x6b\
\x61\x74\0\x2e\x72\x65\x6c\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x73\x79\
\x73\x63\x61\x6c\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\
\x65\x6e\0\x74\x72\x61\x63\x65\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\0\
\x2e\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x6c\x69\x63\x65\x6e\x73\
\x65\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x6f\
\x64\x61\x74\x61\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x49\x43\x45\x4e\x53\
\x45\0\x62\x70\x66\x5f\x6b\x66\x75\x6e\x63\x5f\x63\x61\x6c\x6c\x5f\x74\x65\x73\
\x74\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xaa\0\0\0\
\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5d\x09\0\0\0\0\0\0\xe8\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x49\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x40\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x45\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x58\
\x08\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x0e\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\
\0\0\0\0\0\0\x60\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x80\0\0\0\0\
\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5c\
\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x78\x08\0\0\0\0\0\0\x20\0\0\
\0\0\0\0\0\x0e\0\0\0\x05\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\xa2\0\0\0\
\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc0\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xba\0\0\0\x01\0\0\0\x02\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xcd\0\0\0\0\0\0\0\x2c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc6\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xfc\0\0\0\0\0\0\0\xae\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\xc2\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x98\
\x08\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x0e\0\0\0\x09\0\0\0\x08\0\0\0\0\0\0\0\x10\0\
\0\0\0\0\0\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xac\x06\0\0\0\
\0\0\0\xb8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x07\
\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd8\x08\0\0\0\0\0\0\x80\0\0\
\0\0\0\0\0\x0e\0\0\0\x0b\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x94\0\0\0\
\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\x58\x09\0\0\0\0\0\0\x05\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb2\0\0\0\x02\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x68\x07\0\0\0\0\0\0\xf0\0\0\0\0\0\0\0\x01\0\
\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";
}

#ifdef __cplusplus
struct kprobe_bpf *kprobe_bpf::open(const struct bpf_object_open_opts *opts) { return kprobe_bpf__open_opts(opts); }
struct kprobe_bpf *kprobe_bpf::open_and_load() { return kprobe_bpf__open_and_load(); }
int kprobe_bpf::load(struct kprobe_bpf *skel) { return kprobe_bpf__load(skel); }
int kprobe_bpf::attach(struct kprobe_bpf *skel) { return kprobe_bpf__attach(skel); }
void kprobe_bpf::detach(struct kprobe_bpf *skel) { kprobe_bpf__detach(skel); }
void kprobe_bpf::destroy(struct kprobe_bpf *skel) { kprobe_bpf__destroy(skel); }
const void *kprobe_bpf::elf_bytes(size_t *sz) { return kprobe_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
kprobe_bpf__assert(struct kprobe_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __KPROBE_BPF_SKEL_H__ */
